services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "${PUBLIC_HTTP_PORT:-3080}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - web

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BACKEND_PORT: "${BACKEND_PORT:-5000}"
    ports: 
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    networks:
      - web

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    networks:
      - web

volumes:
  shared:

networks:
  web: