services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.prod
    ports:
      - "${PUBLIC_HTTP_PORT:-80}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - web
    # Uncomment this when ready to serve HTTPS! 
    # volumes:
    # - ../certs:/etc/nginx/certs
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
      args:
        BACKEND_PORT : "${BACKEND_PORT:-5000}"
    expose:
      - "${BACKEND_PORT:-5000}"
    environment:
      - NODE_ENV=production
    volumes:
      - ./shared:/app/shared
    networks:
      - web

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    expose:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ./shared:/app/shared
    networks:
      - web

volumes:
  shared:

networks:
  web: