services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - web
    # Uncomment this when ready to serve HTTPS! 
    # volumes:
    # - ../certs:/etc/nginx/certs
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BACKEND_PORT : "5000"
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./shared:/app/shared
    networks:
      - web

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./shared:/app/shared
    networks:
      - web

volumes:
  shared:

networks:
  web: