services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "${PUBLIC_HTTP_PORT:-3080}:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-5000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
    depends_on:
      - frontend
      - backend
    networks:
      - web

  mongodb:
    image: mongo:4.0
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - db


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BACKEND_PORT: "${BACKEND_PORT:-5000}"
    ports: 
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:${MONGODB_PORT:-27017}/giveapp
      - JWT_SECRET=${JWT_SECRET}
      - CSRF_SECRET=${CSRF_SECRET}
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    networks:
      - web
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    networks:
      - web

volumes:
  shared:
  mongodb_data:

networks:
  web:
  db:
